export const data =  [
    {
      "id": 1,
      "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$dXl2REdjbDROczRHQmhUYnFydVRiUg$dOfgFwjNMFgBdAjGHRj3GN8NfoF8wYsVUDwoa/mqhyc",
      "last_login": "2023-02-20T00:30:22Z",
      "is_superuser": true,
      "username": "Lautaro",
      "first_name": "Felipe",
      "last_name": "Sandim",
      "email": "felipesandimguliermone@gmail.com",
      "is_staff": true,
      "is_active": true,
      "date_joined": "2023-02-20T00:30:11Z",
      "points": 109,
      "medals": 0,
      "image": null,
      "groups": [],
      "user_permissions": []
    },
    {
      "id": 2,
      "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$UXRvem1QeWJTOUFrdEtTSlpjUXBNUw$Vq2ArL+RcxV5wgGMfEh0tSCirmT5CEWqg3RZKGR1g3U",
      "last_login": null,
      "is_superuser": true,
      "username": "Felipe",
      "first_name": "",
      "last_name": "",
      "email": "",
      "is_staff": true,
      "is_active": true,
      "date_joined": "2023-02-20T05:10:14.050001Z",
      "points": 103,
      "medals": 0,
      "image": "",
      "groups": [],
      "user_permissions": []
    },
    {
      "id": 1,
      "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$dXl2REdjbDROczRHQmhUYnFydVRiUg$dOfgFwjNMFgBdAjGHRj3GN8NfoF8wYsVUDwoa/mqhyc",
      "last_login": "2023-02-20T00:30:22Z",
      "is_superuser": true,
      "username": "Mario",
      "first_name": "Felipe",
      "last_name": "Sandim",
      "email": "felipesandimguliermone@gmail.com",
      "is_staff": true,
      "is_active": true,
      "date_joined": "2023-02-20T00:30:11Z",
      "points": 94,
      "medals": 0,
      "image": null,
      "groups": [],
      "user_permissions": []
    },
    {
      "id": 1,
      "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$dXl2REdjbDROczRHQmhUYnFydVRiUg$dOfgFwjNMFgBdAjGHRj3GN8NfoF8wYsVUDwoa/mqhyc",
      "last_login": "2023-02-20T00:30:22Z",
      "is_superuser": true,
      "username": "Test1",
      "first_name": "Felipe",
      "last_name": "Sandim",
      "email": "felipesandimguliermone@gmail.com",
      "is_staff": true,
      "is_active": true,
      "date_joined": "2023-02-20T00:30:11Z",
      "points": 80,
      "medals": 0,
      "image": null,
      "groups": [],
      "user_permissions": []
    },
    {
      "id": 1,
      "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$dXl2REdjbDROczRHQmhUYnFydVRiUg$dOfgFwjNMFgBdAjGHRj3GN8NfoF8wYsVUDwoa/mqhyc",
      "last_login": "2023-02-20T00:30:22Z",
      "is_superuser": true,
      "username": "Santiago",
      "first_name": "Felipe",
      "last_name": "Sandim",
      "email": "felipesandimguliermone@gmail.com",
      "is_staff": true,
      "is_active": true,
      "date_joined": "2023-02-20T00:30:11Z",
      "points": 20,
      "medals": 0,
      "image": null,
      "groups": [],
      "user_permissions": []
    },
    {
      "id": 1,
      "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$dXl2REdjbDROczRHQmhUYnFydVRiUg$dOfgFwjNMFgBdAjGHRj3GN8NfoF8wYsVUDwoa/mqhyc",
      "last_login": "2023-02-20T00:30:22Z",
      "is_superuser": true,
      "username": "DemoDay",
      "first_name": "Felipe",
      "last_name": "Sandim",
      "email": "felipesandimguliermone@gmail.com",
      "is_staff": true,
      "is_active": true,
      "date_joined": "2023-02-20T00:30:11Z",
      "points": 8,
      "medals": 0,
      "image": "https://media.discordapp.net/attachments/1070482671249137674/1079909318037618708/holbertonSchool.jpg?width=480&height=480",
      "groups": [],
      "user_permissions": []
    }
    ]