# Generated by Django 4.1.6 on 2023-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
